name: winter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.1
  flutter_screenutil: ^5.0.2
  get: ^4.6.1
  cloud_firestore: ^2.5.1
  cloud_functions: ^3.0.2
  firebase_auth: ^3.3.4
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_storage: ^10.0.3
  firebase_messaging: ^10.0.6
  firebase_database: ^7.2.1
  firebase_app_check: ^0.0.2+1
  flutter_local_notifications: ^8.0.0
  flutter_lints: ^1.0.0
  google_sign_in: ^5.0.5
  shimmer: ^2.0.0
  loading_dialog: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
    

flutter:

  uses-material-design: true